variable "project_id" {}
variable "project_region" {}
variable "route_mode" {}
variable "ip_address_range_frontend" {}
variable "stack_type" {}
variable "aggregate_interval" {}
variable "include_all_metadata" {}
variable "ip_address_range_backend" {}
variable "ip_address_range_database" {}
variable "allow-internal-traffic" {}
variable "firewall_ports" {}
variable "source_ranges" {}
variable "destination_ranges" {}
variable "source_ranges_clousql" {}
variable "clousql_port" {}
variable "private_ip_type" {}
variable "private_ip_purpose" {}
variable "service" {}
variable "database_version" {}
variable "machine_type" {}
variable "availability_type_regional" {}
variable "edition" {}
variable "environment" {}
variable "db_username" {}
variable "db_password" {}
variable "backup-time" {}
variable "availability_type_zonal" {}
variable "update_track" {}
variable "access_prevention_policy" {}
variable "nearline_storage_age" {}
variable "coldline_storage_age" {}
variable "archive_storage_age" {}
variable "delete_age" {}
variable "key_name" {}
